sudo: required
language: go
go:
  - 1.8.x
  - 1.9.x
go_import_path: github.com/teamwork/spamc
notifications:
  email: false
cache:
  directories:
    - $HOME/gopath/pkg
install:
  - ./bin/setup-travis
script:
  - cd $HOME/gopath/src/github.com/teamwork/spamc
  - ./bin/test -b testsa
  - ./bin/coverage -b testsa
  - ./bin/lint
